### ISSUE TITLE
installing wit-deps instructions

### ISSUE THREAD

**Issue by reematcs** [vados-cosmonic/wasmcon2024-couchbase-workshop#10]
Please make clear as per our convo @ KubeCon adding a column on how to install wit-deps

**Comment by vados-cosmonic** [comment]
Thanks so much for this @reematcs  -- the instructions are [now updated](https://github.com/vados-cosmonic/wasmcon2024-couchbase-workshop/commit/4aff351252a868f1da445ec0ebd1a6e101195836) :)
