### ISSUE TITLE
Ensure TinyGo is installed in the containers

### ISSUE THREAD

**Issue by vados-cosmonic** [vados-cosmonic/wasmcon2024-couchbase-workshop#4]
Unfortunately, TinyGo is relatively difficult to install properly locally.

It needs to be present in both GitPod and the devcontainers setups.

**Comment by ldoguin** [comment]
Both setup use the same image, we are all good with image: laurentdoguin/workspace-couchbase-wash@sha256:c1fdc9ce1af13c9281e525ea125bdd0609f48cdd10ee247194b6ad54c7384d60
